name: check

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check docstyle
        run: |
          pip3 install pydocstyle==6.1.1
          pydocstyle --match=".*\.py"

      - name: Spell-check
        run: |
          pip3 install codespell==2.1.0
          codespell .

      - name: Black linting
        run: |
          pip3 install black==24.10.0
          black . --check

      - name: Run isort
        run: |
          pip3 install isort
          isort . --check-only

      - name: Run Flake8
        run: |
          pip3 install flake8
          flake8 . --max-line-length=100 --show-source
